application: shopplymockup
version: 1
runtime: python
api_version: 1

handlers:

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /list
  script: list.py

- url: /browse
  script: browse.py

- url: .*
  script: main.py
