#!/usr/bin/env python

def mainHeader():
  print '<header>'
  print '<div id="logo">'
  print '<img src="/img/ShopplyLogo.png" alt="Shopply Logo" />'
  print '</div>'
  print '<div id="headerLinks">'
  print 'Home | My Deals | Search'
  print '</div>'
  print '<div id="welcomeUser">'
  print '<div id="userPic">'
  print '<img src="/img/welcomeDave.png" alt="Welcome Dave" />'
  print '</div>'
  print '<div id="welcomeName">'
  print 'Welcome Dave'
  print '</div>'
  print '</div>'
  print '</header>'

print 'Content-Type: text/html \n'
print '<!DOCTYPE html>'
print '<html lang="en">'
print '<head>'
print '<meta charset="utf-8" />'
print '<title>Shopply</title>'
print '<link href="/css/shopply.css" rel="stylesheet" />'
print '<script src="/js/shopply.js"></script>'
print "<link href='http://fonts.googleapis.com/css?family=Nunito' rel='stylesheet' type='text/css'>"
print '</head>'
print '<body onload=initMainPage()>'
mainHeader()
print '<div id="dealsContent">'
print '</div>'
print '</body>'
print '</html>'